name: Push commit to protected branch

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: print
        run: echo "${{ github.ref#refs/tags/ }}"
